### ISSUE TITLE
Symlink semantics

### ISSUE THREAD

**Issue by burdges** [hersle/rmirro#3]
Afaik there are no symlinks in the remarkable's file system, so they could mean whatever you like on the native side.  I guess https://github.com/hersle/rmirro/blob/main/rmirro.py#L27 says you were already thinking about this.

I think "follow-but-copy-on-write" gives one sensible meaning:  If a symlink exists then the target directory or file gets copied over to the remarkable.  If a symlink file is deleted on the remarkable then the symlink is deleted.  If a symlink file is changed on the remarkable, then the symlink is removed and a new regular file is created in its place.  An error/warning occurs if a symlink directory is deleted or has changes, but users could create directory trees containing only symlinked files using `cp -rs`, thus avoiding this problem.

**Comment by kg4zow** [comment]
The reMarkable *software* doesn't create symlinks, but if some other program (like [RCU](http://www.davisr.me/projects/rcu/)) creates them on the tablet's filesystem, the reMarkable software will "follow" them.

Symlinks are how RCU is able to upload custom templates when the `/` filesystem is almost full. It uploads the actual files to `/home/root/.local/share/remarkable/templates/` (in the user storage partition) and creates symlinks in `/usr/share/remarkable/templates/` (in the OS partition, and where the reMarkable software looks for templates) pointing to the real files. When RCU connects to a tablet it checks both directories, and if it finds any real files which don't have the symlinks, it offers to "re-link" them for you automatically. (It does something similar for custom splash screens, but it doesn't use symlinks.)

**Comment by burdges** [comment]
Alright I've long since forgotten why I thought file system didn't support them.

**Comment by hersle** [comment]
Thanks both for your input!

I did think that symlinks could be used for something down the road, but I don't have a very clear idea of exactly what yet. I don't want to complicate things too much.

One idea I have had is to use symlinks to let users browse their reMarkable by tags on the computer. For example to have a top-level `remarkable_by_tags` directory, which includes directories `tag1`, `tag2`, `...` for each tag made on the reMarkable. These folders could contain symlinks `doc1.pdf`, `doc2.pdf`, ... to documents in the main `remarkable` directory. This would be a "read-only" way of finding documents on the reMarkable, so changes made in the `remarkable_by_tags` directory would not be reflected on the reMarkable. The `remarkable_by_tags` folder structure could be remade from scratch at every sync by parsing the reMarkable's file system.
