### ISSUE TITLE
"system can't find file" error for line "proc = subprocess.run(cmd, capture_output=capture, encoding="utf-8")" of rmirro.py.

### ISSUE THREAD

**Issue by fkoenigde** [hersle/rmirro#6]
I made the requirements (passwordless access and shortname remarkable) work. Trying to run rmirro.py either in Visual Studio 2022 (points out line 44 as mentioned above) or via command Line produces the error "FileNotFoundError: [WinError 2]". I tried using ython 3.1 (64bit) or 3.9 (64bit).

Here is the output it produces:
```
Connecting to remarkable
Connected to remarkable
Backing up raw files to C:\remarkable_backup
Traceback (most recent call last):
  File "C:\RMIRRO\rmirro.py", line 490, in <module>
    rm = Remarkable(ssh_name)
  File "C:\RMIRRO\rmirro.py", line 91, in __init__
    self.backup()
  File "C:\RMIRRO\rmirro.py", line 134, in backup
    pc_run(["rsync", "--info=progress2", "-az", "--delete", f"{self.ssh_name}:{self.raw_dir_remote}/", f"{self.backup_dir}/"], exiterror="Failed backing up raw files", capture=False) # --delete deletes files on PC that are no longer on RM
  File "C:\RMIRRO\rmirro.py", line 44, in pc_run
    proc = subprocess.run(cmd, capture_output=capture, encoding="utf-8")
  File "C:\ProgramData\miniconda3\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\miniconda3\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\miniconda3\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

The last thing which seems to happen is creating the Backup folder "remarkable_backup" -> self.backup_dir. 

Any ideas on how to fix this or how build checks for after the point of failure?

**Comment by fkoenigde** [comment]
Turns out ChatGPT sent me done the right track. In Windows 10 the command rsync doesn't exist. However you can install WSL (Windows Subsystem for Linux), which is basically Ubuntu in command line. Now the raw-backup and the meta-data is filled.
Now I get a new error message:
` File "/mnt/a/Termine/Template/RMIRRO/rmirro.py", line 490, in <module>
    rm = Remarkable(ssh_name)
  File "/mnt/a/Termine/Template/RMIRRO/rmirro.py", line 101, in __init__
    metadata = self.read_metadata(id)
  File "/mnt/a/Termine/Template/RMIRRO/rmirro.py", line 147, in read_metadata
    return self.read_json(f"{id}.metadata")
  File "/mnt/a/Termine/Template/RMIRRO/rmirro.py", line 143, in read_json
    return json.loads(self.read_file(filename))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Any ideas on how to fix this or how build checks for after the point of failure?

**Comment by hersle** [comment]
Thanks for reporting this! My motivation for writing this program was that there is no official reMarkable application for Linux, so I have in fact not tested it with Windows yet.

The first issue is that [rsync](https://rsync.samba.org/) is not installed, as you figured out (it usually comes with Linux).
I will make sure to specify that it is a dependency.

The second issue sounds to me that the program encounters empty or erronous metadata files. Can you try the steps below?
1. Delete the `remarkable`, `remarkable_backup` and `remarkable_metadata` folders and run `rmirro.py` again (from a clean state). Does it still give the error?
2. Check the `*.metadata` files in `remarkable_metadata`. Are they empty? If not, can you show me one of them?

**Comment by fkoenigde** [comment]
Thank you for your suggestion. Although simply deleting the folders remarkable_backup and remarkable_metadata - the folder remarkable was not yet created - didn't lead to the desired result, your second suggestion led to fixing the problem. One (and only one) of the *.metadata files was empty. In the past, I had a lot of trouble using the built-in desktop cloud of remarkable (it simply didn't synchronize all of the files, whatever I tried), which, apart from privacy concerns, led me to look for another solution. I simply deleted the corrupted *.metadata file on my remarkable. Now the code is working fine.

Since it proved difficult to get to the point I have to suggestions for change:
1. Change the order of the requirements and put "[rsync](https://rsync.samba.org/) (comes with most Linux distributions, by default).` first. You might add the following: In order to run the script in Windows 10 you have to install the [WIndows Subsystem for Linux](https://sanajitghosh.medium.com/run-python-codes-develop-ml-models-using-wsl-windows-10-40f8bb39fd45) and establish the other requirements within WSL.
2. Assuming my problem is not uncommon it would be useful to implement a check if a `*.metadata` file is corrupted/empty, offering to delete the concerned file from the remarkable. Unfortunately ChatGPTs ideas just didn't work out with my abilites to create said code.

**Comment by hersle** [comment]
Thanks a lot! Great to hear you got it working on Windows.
I will consider following up your suggestions :)
