### ISSUE TITLE
KeyError on first run

### ISSUE THREAD

**Issue by Ph-St** [hersle/rmirro#9]
After having set up ssh requirements and installing rmrl, on first run I get the following error message:

```
./rmirro.py remarkable
Connecting to remarkable
Connected to remarkable
Backing up raw files to /home/xxx/Downloads/rmirro-main/remarkable_backup
    817.042.875 100%    3,33MB/s    0:03:53 (xfr#6220, to-chk=0/6759)   
Downloading metadata to /home/xxx/Downloads/rmirro-main/remarkable_metadata
        147.299 100%    1,35MB/s    0:00:00 (xfr#418, to-chk=0/419)  
Traceback (most recent call last):
  File "/home/xxx/Downloads/rmirro-main/./rmirro.py", line 490, in <module>
    rm = Remarkable(ssh_name)
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/Downloads/rmirro-main/./rmirro.py", line 103, in __init__
    self.children_cache[parent_id].append(id)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: None
```

Software version on remarkable is 3.11.2.5. I run rmirro on Arch.

Any tipps how this could be resolved? Thanks!

**Comment by hersle** [comment]
Is the folder `remarkable_metadata` populated with `*.metadata` files?
Can you inspect the contents of a few of them, and post here?
Do they have the field `parent: ...`?

**Comment by Ph-St** [comment]
Thanks for the quick reply!

The folder is populated and it seems that all files contain the parent field:

```
ls | wc -l
418

grep parent * | wc -l
418
```

Here's a random file:

```
{
    "deleted": false,
    "lastModified": "1643973403974",
    "lastOpened": "1644566744592",
    "lastOpenedPage": 0,
    "metadatamodified": false,
    "modified": true,
    "parent": "ce34876e-8244-4286-8755-07709bfd2bd3",
    "pinned": false,
    "synced": false,
    "type": "DocumentType",
    "version": 2,
    "visibleName": "michael aaron londquist Utopian Dialog and Science Fiction"
}
```

Do you want me to post more?

**Comment by hersle** [comment]
Can you download the diagnostic change I just made by running `git pull` (or re-clone the repository), and then post the output of `./rmirro.py remarkable --verbose`?

**Comment by Ph-St** [comment]
Ok, it breaks on a file that has 

`"parent": null`

I made another search for this and it seems that two files are afflicted. Here they are:

```
{
    "deleted": false,
    "lastModified": null,
    "metadatamodified": true,
    "modified": true,
    "parent": null,
    "pinned": false,
    "synced": false,
    "type": "CollectionType",
    "version": 2,
    "visibleName": "Defences"
}

{
    "deleted": false,
    "lastModified": null,
    "metadatamodified": true,
    "modified": true,
    "parent": null,
    "pinned": false,
    "synced": false,
    "type": "CollectionType",
    "version": 1,
    "visibleName": "Platon Anthologie"
}
```

**Comment by hersle** [comment]
Hmm, ok, thanks! Are these two folders located at the top/root level of your remarkable's file system?

**Comment by Ph-St** [comment]
Yes, they are!

**Comment by hersle** [comment]
Do you remember exactly how these folders were created?
In other words, are you able to reproduce the steps you took to create another folder that gets `"parent": null`?

I just updated to `3.11.2.5` and created a top-level folder on my reMarkable, but that gets `"parent": ""`.
Perhaps you did something slightly different?

**Comment by Ph-St** [comment]
Hm, hard to say. These are pretty old folders and I tried all sorts of 3rd party tools. Perhaps one of them was responsible. So should I just make new folders, move all the files and then delete the offending folders?

**Comment by hersle** [comment]
Yes, I think that should work!

After moving the files to the new folders, try to not only trash the old folders, but also delete them completely from the trash.

Let me know how it goes :smiley:

**Comment by Ph-St** [comment]
Works, many thanks for helping me solve this!

Now I only have to write a wrapper for rmrl, but I think that should be okay...

**Comment by hersle** [comment]
Great! If you succeed in wrapping it in a `render_rmrl.py` script, I would be happy to add that here.

**Comment by Ph-St** [comment]
I wrote the script (see below) and it runs fine on some files. On others, unfortunately, rmrl breaks, so I suppose it's not better than maxio. It would be nice if we had a way to run a chain of renderers to increase the chances of a good result. Also, instead of stopping on error, perhaps it would be better to produce a pdf with a message about the failed rendering and continue for other files. What do you think?

```
#!/usr/bin/python3

# This method uses the third-party renderer rmrl to render reMarkable documents locally on the computer.
# It downloads the raw reMarkable files to the computer and renders them locally.
#
# It requires the python module rmrl (https://github.com/rschroll/rmrl/) and SSH access to the reMarkable (to download the raw files), but no USB connection.
#
# It fails in some cases.
#
# To use a different third-party renderer, wrap it in a script with call signature like this one!

import sys
import os.path
import subprocess
from rmrl import render

def render_rmrl(input, output):
    stream = render(input)
    with open(output, "wb") as out_file:
        out_file.write(stream.read())
    


if __name__ == "__main__":
    args = sys.argv[1:]
    assert len(args) == 2, "usage: render_rmrl.py infile outfile"

    infile = args[0]
    outfile = args[1]

    status = render_rmrl(infile, outfile)
    
    exit(status)
```
